-- @/Users/joanneuwera/CSY2080/coursework/03_insert.sql
-- employees

INSERT INTO employees (employee_id, firstname, surname, date_of_birth, mobile_number, town, postcode, email, graduated, grade)
VALUES (00000,'ADAM','CLARK','24-APR-2003','07912674918','NORTHAMPTON','NN14 4JH','ADAMC12@GMAIL.COM','Y','A-');

INSERT INTO employees (employee_id, firstname, surname, date_of_birth, mobile_number, town, postcode, email, graduated, grade)
VALUES (00001,'BEN','JIMMY','5-NOV-2003','07912630724','LONDON','SE9 3KL','BEN200@HOTMAIL.COM',DEFAULT,'B+');

INSERT INTO employees 
VALUES (00002,'IZZY','AHMED','28-MAR-2004','07943319016','BIRMINGHAM','B76 1AB','IZZYA@OUTLOOK.CO.UK','N','NA');

INSERT INTO employees 
VALUES (00003,'SARA','LEE','21-NOV-2002','07955541294','NOTTINGHAM','NG19 7PA','SARA202@GMAIL.COM','Y','C+');

INSERT INTO employees 
VALUES (00004,'FRANK','PLUS','1-DEC-2001','07922367910','NORTHAMPTON','NN16 9UA','FRANKP@HOTMAIL.COM','N','NA');

-- projects

INSERT INTO projects (project_id, project_name, project_description)
VALUES(11110,'QUERY QUEST','INFORMATION RETRIEVAL THROUGH ADVANCED ALGORITHMS AND MACHIENE LEARNING');

INSERT INTO projects (project_id, project_name, project_description)
VALUES(11111,'CODE CRAFT','A COLLABORATIVE APPROACH TO SOFTWARE DEVELOPMENT, EMPHASIZING CRAFTSMANSHIP, EFFICIENCY, AND CREATIVITY TO PRODUCE HIGH-QUALITY CODE');

INSERT INTO projects 
VALUES(11112,'DATA DYNAMO','DYNAMICALLY OPTIMISING AND LEVERAGING THE POWER OF DATA THROUGH ADVANCED ANALYTICS AND MACHINE LEARNING');

INSERT INTO projects 
VALUES(11113,'CYBER SHEILD','CYBER SECURITY INITIATIVE DESIGNED TO FORTIFY DIGITAL ENVIROMENT EMPLOYING ADVANCED TECHNOLOGIES');

INSERT INTO projects 
VALUES(11114,'ECO SENSE','COMMITTED TO PROMOTING ENVIRONMENTAL CONSCIOUSNESS AND SUSTAINABLE PRACTICES');

-- team_members

INSERT INTO team_members (team_member_id,employee_id, project_id)
VALUES (22220,00000,11110);

INSERT INTO team_members (team_member_id,employee_id, project_id)
VALUES (22221,00001,11111);

INSERT INTO team_members 
VALUES (22222,00002,11112);

INSERT INTO team_members 
VALUES (22223,00003,11113);

INSERT INTO team_members
VALUES (22224,00004,11114);

-- stages

INSERT INTO stages (stage_number, stage_title)
VALUES (1,'PLANNING');

INSERT INTO stages (stage_number, stage_title)
VALUES (2,'DESIGN');

INSERT INTO stages 
VALUES (3,'DEVELOPMENT');

INSERT INTO stages 
VALUES (4,'TESTING');

INSERT INTO stages 
VALUES (5,'DEPLOYMENT');

-- skills

INSERT INTO skills (skill_id, skill_name, skill_description, skill_level, stage_number)
VALUES (330,'DATA MODELING','SKILLED IN CREATING CONCEPTUAL, LOGICAL, AND PHYSICAL DATA MODELS, TRANSLATING BUSINESS REQUIREMENTS INTO WELL-STRUCTURED DATABASES',1,2);

INSERT INTO skills (skill_id, skill_name, skill_description, skill_level, stage_number)
VALUES (331,'BACKUP AND RECOVERY','COMPETENT IN DESIGNING AND IMPLEMENTING ROBUST BACKUP AND RECOVERY STRATEGIES TO SAFEGUARD DATA AND MINIMISE DOWNTIME IN CASE OF FAILURES',3,2);

INSERT INTO skills
VALUES (332,'DATA SECURITY AND CONTROL','IMPLEMENTING SECURITY MEASURES, INCLUDING ACCESS CONTROL, ENCRYPTION, TO PROTECT SENSITIVE DATA AND ENSURE COMPLIANCE WITH SECURITY STANDARDS',3,3);

INSERT INTO skills
VALUES (333,'DATABASE ADMINISTRATION','EXPERIENCED IN ORACLE DATABASE ADMINISTRATION TASKS, INCLUDING INSTALLATION, CONFIGURATION, MONITORING, BACKUP, RECOVERY, AND USER MANAGEMENT',2,4);

INSERT INTO skills
VALUES (334,'TRANSACTION MANAGEMENT','MANAGING DATABASE TRANSACTIONS, ENSURING THE ACID PROPERTIES (ATOMICITY, CONSISTENCY, ISOLATION, DURABILITY) FOR RELIABLE AND SECURE DATA OPERATIONS',3,5);

-- employee_skills 

INSERT INTO employee_skills (employee_id, skill_id)
VALUES (00000,330);

INSERT INTO employee_skills (employee_id, skill_id)
VALUES (00001,331);

INSERT INTO employee_skills
VALUES (00002,332);

INSERT INTO employee_skills
VALUES (00003,333);

INSERT INTO employee_skills
VALUES (00004,334);

-- project_stages

INSERT INTO project_stages (project_stage_id, project_id, stage_number, start_date, duration)
VALUES (55550,11110,1,'10-SEP-2023',120);

INSERT INTO project_stages (project_stage_id, project_id, stage_number, start_date, duration)
VALUES (55551,11111,2,'10-OCT-2023',75);

INSERT INTO project_stages
VALUES (55552,11112,3,'11-AUG-2023',200);

INSERT INTO project_stages
VALUES (55553,11113,4,'10-DEC-2023',60);

INSERT INTO project_stages
VALUES (55554,11114,5,'10-SEP-2023',180);

-- tasks

INSERT INTO tasks (task_id, team_member_id, project_stage_id, task_required)
VALUES (66660,22220,55550,'Y');

INSERT INTO tasks (task_id, team_member_id, project_stage_id, task_required)
VALUES (66661,22221,55551,'N');

INSERT INTO tasks 
VALUES (66662,22222,55552,DEFAULT);

INSERT INTO tasks
VALUES (66663,22223,55553,'N');

INSERT INTO tasks 
VALUES (66664,22224,55554,'Y');

-- resources 

INSERT INTO resources (resource_id, resource_name, resource_description, price)
VALUES (77770,'DATABASE FINDER','HELPS DATABASES TO BE CORRECT AND IS ABLE TO FIX ANY INCORRECTIONS',99.99);

INSERT INTO resources (resource_id, resource_name, resource_description, price)
VALUES (77771,'SEC GUARD','A SECURITY FOR ORACLE DATABASES, KEEPS SENSITIVE DATA SECURE',75.80);

INSERT INTO resources 
VALUES (77772,'QUERY OPTIMIZER PLUS','AN ORACLE TOOL, OPTIMIZES SQL QUERIES, ENHANCES RESPONSE TIMES, AND SUGGESTS INDEXING FOR EFFICIENCY',101.50);

INSERT INTO resources 
VALUES (77773,'DATA HARMONY LITE','A SIMPLIFIED DATA QUALITY TOOL, PROFILES, AND CLEANSES FOR CONSISTENCY',30.42);

INSERT INTO resources 
VALUES (77774,'SETUP QUERY','AN EASY WAY TO BE ABLE TO SETUP ORACLE AND MAKE A QUERY AND ABLE TO SAVE IT',50.89);

-- task resources 

INSERT INTO task_resources (task_id, resource_id)
VALUES (66660,77770);

INSERT INTO task_resources (task_id, resource_id)
VALUES (66661,77771);

INSERT INTO task_resources 
VALUES (66662,77772);

INSERT INTO task_resources 
VALUES (66663,77773);

INSERT INTO task_resources 
VALUES (66664,77774);
